#!/bin/bash

if [[ $# == 0 ]]; then
	echo "Usage :"
	echo "$0 <nb_faces> <nb_dies>"
	echo "ex: $0 20"
else
	if [[ $# == 2 ]]; then
		for ((i=1; i<=$2; i++)) ; do
			echo $(($(($RANDOM % $1)) + 1 ))
		done
	else
		echo $(($(($RANDOM % $1)) + 1 ))
	fi
fi
